name: Docker Build And Push To AliCloud
on:
  push:
    branches: [master]
env:
  IMAGE_URL: registry.cn-hangzhou.aliyuncs.com/golden/goodking_bq-github-io
jobs:
  setup-build-Push-deploy:
    name: Setup, Build, Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          cat>Dockerfile<<EOF
          FROM nginx:alpine 
          COPY . /usr/share/nginx/html
          EOF
          docker build -t ${IMAGE_URL}:${GITHUB_SHA:0:7} .
          docker tag ${IMAGE_URL}:${GITHUB_SHA:0:7} ${IMAGE_URL}:latest
      - name: Docker Login
        run: docker login -u ${{ secrets.ALI_USERNAME }} -p ${{ secrets.ALI_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - name: Docker Push
        run: |
          docker push ${IMAGE_URL}:${GITHUB_SHA:0:7}
          docker push ${IMAGE_URL}:latest
